### ISSUE TITLE
Null relationships cause empty objects in the response

### ISSUE THREAD

**Issue by bmac** [endpoints/endpoints#4] opened 2015-01-23 22:09 UTC
I have a relationship that can hold a null value. When I request data with the included relationship. I get an empty object in the relationship's objects array if one if the main records has a null in its foreign key field. 
![screen shot 2015-01-23 at 5 06 51 pm](https://cloud.githubusercontent.com/assets/54056/5883654/6eaf3538-a322-11e4-9b11-185df9b04baa.png)

**Comment by tkellen** [comment] 2015-01-23 22:11
Note to self: implement this sort of relation in https://github.com/tkellen/fantasy-database

**Comment by tkellen** [comment] 2015-01-23 22:19
I suspect the issue is here:
https://github.com/endpoints/endpoints-source-bookshelf/blob/master/lib/format/api.js#L41-L56

Will investigate Monday.

**Comment by tkellen** [comment] 2015-01-25 17:18
Resolved in https://github.com/endpoints/endpoints-source-bookshelf/commit/91df841321500ba7ccb7abf989b0662596561bcc

**Closed by tkellen** 2015-01-25 17:18 UTC
